import { app, BrowserWindow, shell, session, autoUpdater, ipcMain, screen } from "electron";
import isDev from "electron-is-dev";
import makeIpcRoutes from "./main/routes/index";
import path from "path";
import child_process from "child_process";
import fs from "fs-extra";
import fetch from "node-fetch";
import { pipeline } from "stream/promises";
import AdmZip from "adm-zip";

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

export const hasPortableFile = fs.existsSync(path.resolve(app.getPath("exe"), "..", "portable"));
const squirrelUpdateExe = path.resolve(app.getPath("exe"), "..", "..", "Update.exe");
const hasSquirrelUpdater = process.platform === "win32" && fs.existsSync(squirrelUpdateExe);
const forceManualUpdatePrompt = process.argv.includes("--force-update-prompt");
export const cacheDir = hasPortableFile ? path.resolve(app.getPath("exe"), "..", "electron_cache") : path.join(app.getPath("userData"));
export const proxyFile = path.resolve(cacheDir, "proxy");
export const steamGridDbApiKeyFile = path.resolve(cacheDir, "steamgriddb-api-key");
export const gameIconSizeFile = path.resolve(cacheDir, "game-icon-size");
export const SYS_SETTINGS = {
  proxy: readFile(proxyFile),
  steamGridDbApiKey: readFile(steamGridDbApiKeyFile),
  gameIconSize: readFile(gameIconSizeFile) || "180",
};
let updateDownloaded = false;

function readFile(path: string) : string {
  try {
    return fs.readFileSync(path, "utf-8");
  } catch (e) {
    return "";
  }
}

ipcMain.handle("check-status", () => updateDownloaded);
ipcMain.handle("is-manual-update-only", () => hasPortableFile || !hasSquirrelUpdater);

const githubLatestReleaseUrl = "https://api.github.com/repos/Casual-Gamer8001/RyuSAK/releases/latest";

const shellQuote = (value: string) => `'${value.replace(/'/g, "''")}'`;

const RELEASES_PAGE_URL = "https://github.com/Casual-Gamer8001/RyuSAK/releases/latest";

const shellQuoteSh = (value: string) => `'${value.replace(/'/g, "'\\''")}'`;

// Download the newest release asset whose name matches `matcher` into the temp dir.
const downloadLatestAsset = async (matcher: RegExp) => {
  const response = await fetch(githubLatestReleaseUrl, {
    headers: {
      "User-Agent": `RyuSAK/${app.getVersion()}`
    }
  });

  if (!response.ok) {
    throw new Error(`GitHub release check failed with ${response.status} ${response.statusText}`);
  }

  const release = await response.json() as any;
  const asset = (release.assets || []).find((item: any) => matcher.test(item.name || ""));

  if (!asset?.browser_download_url) {
    throw new Error("Could not find a matching RyuSAK download in the latest GitHub release.");
  }

  const downloadPath = path.join(app.getPath("temp"), asset.name);
  const assetResponse = await fetch(asset.browser_download_url, {
    headers: {
      "User-Agent": `RyuSAK/${app.getVersion()}`
    }
  });

  if (!assetResponse.ok || !assetResponse.body) {
    throw new Error(`Download failed with ${assetResponse.status} ${assetResponse.statusText}`);
  }

  await pipeline(assetResponse.body as any, fs.createWriteStream(downloadPath));
  return downloadPath;
};

// Linux/Steam Deck ships as a portable zip, so "update" means: download the new zip,
// replace the app files in place (keeping the user's electron_cache), and relaunch.
const installManualUpdateLinux = async () => {
  const zipPath = await downloadLatestAsset(/^RyuSAK-.*-steamdeck-linux-x64\.zip$/i);
  const stamp = Date.now();
  const extractDir = path.join(app.getPath("temp"), `ryusak-update-${stamp}`);
  await fs.remove(extractDir);
  await fs.ensureDir(extractDir);

  const archive = new AdmZip(zipPath);
  // Preserve the Unix executable bits stored in the archive (adm-zip drops them by default).
  (archive.extractAllTo as (targetPath: string, overwrite?: boolean, keepOriginalPermission?: boolean) => void)(extractDir, true, true);

  // The archive holds a single top-level folder (RyuSAK-linux-x64) with the RyuSAK binary.
  let newAppDir = path.join(extractDir, "RyuSAK-linux-x64");
  if (!fs.existsSync(path.join(newAppDir, "RyuSAK"))) {
    const candidate = fs.readdirSync(extractDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => path.join(extractDir, entry.name))
      .find((dir) => fs.existsSync(path.join(dir, "RyuSAK")));
    if (candidate) {
      newAppDir = candidate;
    }
  }

  if (!fs.existsSync(path.join(newAppDir, "RyuSAK"))) {
    throw new Error("Downloaded Linux archive did not contain a RyuSAK executable.");
  }

  const appDir = path.resolve(app.getPath("exe"), "..");
  const exePath = app.getPath("exe");
  const scriptPath = path.join(app.getPath("temp"), `ryusak-update-${stamp}.sh`);

  const script = [
    "#!/usr/bin/env bash",
    `APP_DIR=${shellQuoteSh(appDir)}`,
    `NEW_DIR=${shellQuoteSh(newAppDir)}`,
    `EXE=${shellQuoteSh(exePath)}`,
    `ZIP=${shellQuoteSh(zipPath)}`,
    `EXTRACT=${shellQuoteSh(extractDir)}`,
    `SELF=${shellQuoteSh(scriptPath)}`,
    `PID=${process.pid}`,
    "# Wait for RyuSAK to exit (up to 5 minutes) before touching its files.",
    "for _ in $(seq 1 600); do kill -0 \"$PID\" 2>/dev/null || break; sleep 0.5; done",
    "# If it is somehow still running, abort rather than modify a live install.",
    "if kill -0 \"$PID\" 2>/dev/null; then exit 0; fi",
    "# Overlay the new build; electron_cache (user settings) is left in place.",
    "if cp -a \"$NEW_DIR\"/. \"$APP_DIR\"/ 2>/dev/null; then",
    hasPortableFile ? "  : # keep the portable marker" : "  rm -f \"$APP_DIR/portable\"",
    "  chmod +x \"$APP_DIR/RyuSAK\" \"$APP_DIR/chrome_crashpad_handler\" \"$APP_DIR/chrome-sandbox\" 2>/dev/null || true",
    "  rm -rf \"$EXTRACT\" \"$ZIP\" 2>/dev/null || true",
    "fi",
    "# Relaunch (Steam Deck / portable needs --no-sandbox) and remove this script.",
    "chmod +x \"$EXE\" 2>/dev/null || true",
    "nohup \"$EXE\" --no-sandbox >/dev/null 2>&1 &",
    "rm -f \"$SELF\" 2>/dev/null || true",
    ""
  ].join("\n");

  await fs.writeFile(scriptPath, script, { encoding: "utf8", mode: 0o755 });
  const child = child_process.spawn("bash", [scriptPath], {
    detached: true,
    stdio: "ignore"
  });
  child.unref();
  app.quit();
};

ipcMain.handle("install-manual-update", async () => {
  try {
    if (process.platform === "linux") {
      await installManualUpdateLinux();
      return { ok: true };
    }

    if (process.platform !== "win32") {
      // No packaged installer for this platform (e.g. macOS): open the releases page instead.
      await shell.openExternal(RELEASES_PAGE_URL);
      return { ok: true };
    }

    const installerPath = await downloadLatestAsset(/^RyuSAK-.*-Setup\.exe$/i);
    const installDir = path.resolve(app.getPath("exe"), "..");
    const relaunchExe = process.execPath;
    const scriptPath = path.join(app.getPath("temp"), `ryusak-update-${Date.now()}.ps1`);
    const installerArgs = [
      "/VERYSILENT",
      "/SUPPRESSMSGBOXES",
      "/NORESTART",
      `/DIR=${installDir}`,
      ...(hasPortableFile ? ["/PORTABLE=1"] : [])
    ];

    const script = [
      "$ErrorActionPreference = \"Stop\"",
      `$installer = ${shellQuote(installerPath)}`,
      `$arguments = @(${installerArgs.map(shellQuote).join(", ")})`,
      `$relaunchExe = ${shellQuote(relaunchExe)}`,
      "Add-Type -AssemblyName System.Windows.Forms",
      "Add-Type -AssemblyName System.Drawing",
      "$form = New-Object System.Windows.Forms.Form",
      "$form.Text = \"Updating RyuSAK\"",
      "$form.Width = 420",
      "$form.Height = 150",
      "$form.StartPosition = \"CenterScreen\"",
      "$form.FormBorderStyle = \"FixedDialog\"",
      "$form.ControlBox = $false",
      "$label = New-Object System.Windows.Forms.Label",
      "$label.Text = \"Preparing update...\"",
      "$label.AutoSize = $true",
      "$label.Left = 24",
      "$label.Top = 22",
      "$progress = New-Object System.Windows.Forms.ProgressBar",
      "$progress.Style = \"Marquee\"",
      "$progress.MarqueeAnimationSpeed = 30",
      "$progress.Left = 24",
      "$progress.Top = 58",
      "$progress.Width = 360",
      "$progress.Height = 24",
      "$form.Controls.Add($label)",
      "$form.Controls.Add($progress)",
      "$form.Show()",
      "[System.Windows.Forms.Application]::DoEvents()",
      "Wait-Process -Id " + process.pid + " -ErrorAction SilentlyContinue",
      "$label.Text = \"Installing update...\"",
      "[System.Windows.Forms.Application]::DoEvents()",
      "$installerProcess = Start-Process -FilePath $installer -ArgumentList $arguments -PassThru",
      "while (-not $installerProcess.HasExited) { [System.Windows.Forms.Application]::DoEvents(); Start-Sleep -Milliseconds 100 }",
      "$label.Text = \"Restarting RyuSAK...\"",
      "[System.Windows.Forms.Application]::DoEvents()",
      "Start-Process -FilePath $relaunchExe",
      "$form.Close()",
      `Remove-Item -LiteralPath ${shellQuote(scriptPath)} -Force -ErrorAction SilentlyContinue`
    ].join("\r\n");

    await fs.writeFile(scriptPath, script, "utf8");
    const child = child_process.spawn("cmd.exe", [
      "/c",
      "start",
      "\"\"",
      "powershell.exe",
      "-NoProfile",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      scriptPath
    ], {
      detached: true,
      stdio: "ignore",
      windowsHide: false
    });
    child.unref();
    app.quit();
    return { ok: true };
  } catch (error) {
    console.error(error);
    return { ok: false, error: error instanceof Error ? error.message : String(error) };
  }
});

// Don't use appData to store cache if portable mode is enabled
if (hasPortableFile) {
  fs.ensureDirSync(cacheDir);
  app.setPath("userData", cacheDir);
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) { // eslint-disable-line global-require
  app.quit();
}

const gotTheLock = app.requestSingleInstanceLock();
let mainWindow: BrowserWindow;

const handleStartupEvent = function () {
  if (process.platform !== "win32") {
    return false;
  }

  const appFolder = path.resolve(process.execPath, "..");
  const rootAtomFolder = path.resolve(appFolder, "..");
  const updateDotExe = path.resolve(path.join(rootAtomFolder, "Update.exe"));
  const exeName = path.basename(process.execPath);

  const spawn = function (command: any, args: any) {
    let spawnedProcess;

    try {
      spawnedProcess = child_process.spawn(command, args, { detached: true });
    } catch (error) {
      console.error(error);
    }

    return spawnedProcess;
  };

  const spawnUpdate = function (args: any) {
    return spawn(updateDotExe, args);
  };

  const squirrelCommand = process.argv[1];
  switch (squirrelCommand) {
    case "--squirrel-install":
      spawnUpdate(["--createShortcut", exeName]);
      return false;
    case "--squirrel-updated":
      setTimeout(app.quit, 1000);
      return true;
    case "--squirrel-uninstall":
      app.quit();
      try {
        fs.removeSync(app.getPath("userData"));
      } catch (e) {
        console.error(e);
      }
      spawnUpdate(["--removeShortcut", exeName]);
      return true;
    case "--squirrel-obsolete":
      app.quit();
      return true;
  }
};

if (handleStartupEvent()) {
  process.exit(0);
}

const createWindow = (): void => {
  mainWindow = new BrowserWindow({
    title: `${app.getName()} v${app.getVersion()}`,
    autoHideMenuBar: true,
    show: false,
    minHeight: 680,
    minWidth: 920,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    }
  });

  makeIpcRoutes(mainWindow);

  mainWindow.webContents.on("did-finish-load", function () {
    const displays = screen.getAllDisplays();
    const display = displays.find((d) => d.bounds.x !== 0 || d.bounds.y !== 0) || displays[0];

    mainWindow.setSize(Math.min(display.bounds.width, 1280), Math.min(display.bounds.width, 860));
    mainWindow.center();
    mainWindow.show();

    if (hasPortableFile || !hasSquirrelUpdater) {
      mainWindow.webContents.send("manual-update-only");
    }
    if (forceManualUpdatePrompt) {
      mainWindow.webContents.send("force-manual-update-prompt");
    }
    else if (hasSquirrelUpdater && !isDev && process.platform === "win32") {
      const feed = `https://update.electronjs.org/Casual-Gamer8001/RyuSAK/${process.platform}-${process.arch}/${app.getVersion()}`;

      autoUpdater.setFeedURL({
        url: feed
      });

      // Check updates every 10 min, and at startup
      setInterval(() => {
        autoUpdater.checkForUpdates();
      }, 10 * 60 * 1000);

      autoUpdater.checkForUpdates();

      autoUpdater.on("update-available", () => mainWindow.webContents.send("update-available"));
      autoUpdater.on("update-downloaded", () => {
        updateDownloaded = true;
        mainWindow.webContents.send("update-downloaded");
      });
      ipcMain.on("reboot-after-download", () => autoUpdater.quitAndInstall());
    }
  });

  mainWindow.webContents.on("new-window", function(e, url) {
    e.preventDefault();
    shell.openExternal(url);
  });

  mainWindow.on("page-title-updated", function (e) {
    e.preventDefault();
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  let cspHeader = "default-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/ 'unsafe-inline'; img-src 'self' data: https://*;";

  // "unsafe-eval" is required by webpack in development
  if (process.env.NODE_ENV === "development") {
    cspHeader = "default-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/ 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https://*;";
  }

  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [cspHeader]
      }
    });
  });
};

// Do not allow application to be launched twice
if (!gotTheLock) {
  app.quit();
} else {
  app.on("second-instance", () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });

  // Some APIs can only be used after Electron is ready.
  app.whenReady().then(createWindow);
}

app.on("window-all-closed", () => {
  app.quit();
});
